### ISSUE TITLE
pull request error 

### ISSUE THREAD

**Issue by Nilfgardian** [DMU-CTEC2902-2022/React_Team#15]
Pull Request failed due to unforeseen circumstances 
![image](https://user-images.githubusercontent.com/98946279/163015430-29b4a177-130e-426f-b6bf-efba4a466306.png)

**Comment by vovafish** [comment]
try 
Step 1: From your project repository, bring in the changes and test.

git fetch origin
git checkout -b Reegan origin/Reegan
git merge main
Step 2: Merge the changes and update on GitHub.

git checkout main
git merge --no-ff Reegan
git push origin main

**Comment by vovafish** [comment]
or to get back the initial connection link
`<add name="DefaultConnection" connectionString="Data Source=(LocalDb)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\aspnet-InformationandTechnologyCollege-20220217094051.mdf;Initial Catalog=aspnet-InformationandTechnologyCollege-20220217094051;Integrated Security=True" providerName="System.Data.SqlClient" />`
