### ISSUE TITLE
Adding two more courses onto course page

### ISSUE THREAD

**Issue by Nilfgardian** [DMU-CTEC2902-2022/React_Team#16]
Course page requires information about two more courses:  Software Engineering, Cyber Security and their respective modules.
![Annotation 2022-04-12 181602 PNG](https://user-images.githubusercontent.com/98946279/163023009-9abc1688-2985-4ff6-a26f-95df2fdd024a.jpg)

**Comment by vovafish** [comment]
yeah there is
you just looking at the old version
