### ISSUE TITLE
Courses links name change

### ISSUE THREAD

**Issue by Nilfgardian** [DMU-CTEC2902-2022/React_Team#20]
links to courses need renaming from the default name to their course name, found in most recent version of the application.
![Capture12](https://user-images.githubusercontent.com/98946279/163245875-b52d8bef-d221-41be-b833-bb92dedccc3b.PNG)

**Comment by vovafish** [comment]
yeah ill do it tomorrow
thanks

**Comment by vovafish** [comment]
fixed
