### ISSUE TITLE
User usability enhancement 

### ISSUE THREAD

**Issue by Nilfgardian** [DMU-CTEC2902-2022/React_Team#22]
Register button colour is currently blending into the page background, for usability purposes and to prevent confusion from the user should be changed so that it is more visible.  thanks in advance. 
![Annotation 2022-04-13 193552](https://user-images.githubusercontent.com/98946279/163250687-bf02f8ef-2d30-4683-b1b8-8856d14d9d95.png)

**Comment by vovafish** [comment]
fixed
